site_name: API.log
theme:
    name: material
    features:
        - content.code.copy
        - navigation.footer
        - search.suggest
        - search.highlight
markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - attr_list
    - md_in_html
extra:
    generator: false
    quote: "Talk is cheap. Show me the code."