site_name: API.log
site_description: The developer's personal log, filtering the noise of the AI world into hard-won findings.
site_url: http://www.example.com
theme:
    name: material
    features:
        - content.code.copy
        - navigation.footer
        - search.suggest
        - search.highlight
        # - navigation.indexes
markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - attr_list
    - md_in_html
extra:
    generator: false
    # social:
    #     - icon: fontawesome/brands/mastodon
    #       name: squidfunk on Mastodon
    #       link: https://fosstodon.org/@squidfunk
plugins:
    - search
    - blog:
        blog_toc: true
nav:
  - Home: index.md
  - Blog:
     - blog/index.md
     - blog/posts/llamafile_docker.md